# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkhD8mA5zrnIlmv3CLUhD5-Fk3Txj-An
"""

import tkinter as tk
import random

# Define the consonants and their names in Thai
consonants = [
    {"symbol": "ก", "name": "gor kai"},
    {"symbol": "ข", "name": "khor khai"},
    {"symbol": "ค", "name": "khor khwai"},
    {"symbol": "ง", "name": "ngor ngu"},
    {"symbol": "จ", "name": "jor jan"},
    {"symbol": "ฉ", "name": "chor ching"},
    {"symbol": "ช", "name": "chor chang"},
    {"symbol": "ซ", "name": "sor so"},
    {"symbol": "ฌ", "name": "chor chao"},
    {"symbol": "ญ", "name": "yor ying"}
]

class FlashcardGame(tk.Tk):
    def __init__(self):
        super().__init__()

        self.title("Thai Consonant Flashcards")
        self.geometry("400x300")

        # Initialize the first consonant and name
        self.current_card = random.choice(consonants)

        # Label to display the consonant or name
        self.card_label = tk.Label(self, text=self.current_card["symbol"], font=("Helvetica", 50), width=10, height=5, relief="solid")
        self.card_label.pack(pady=50)

        # Button to flip the card
        self.flip_button = tk.Button(self, text="Flip Card", font=("Helvetica", 14), command=self.flip_card)
        self.flip_button.pack(pady=20)

    def flip_card(self):
        if self.card_label["text"] == self.current_card["symbol"]:
            # Show the name of the consonant on flip
            self.card_label.config(text=self.current_card["name"])
        else:
            # Choose a new random consonant and display its symbol
            self.current_card = random.choice(consonants)
            self.card_label.config(text=self.current_card["symbol"])

if __name__ == "__main__":
    game = FlashcardGame()
    game.mainloop()